create PACKAGE MARK_PACKAGE AS

PROCEDURE ADD_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE, 
    MRK IN MARK.MARK%TYPE
);

PROCEDURE DELETE_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE
);

PROCEDURE UPDATE_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE,
    MRK IN MARK.MARK%TYPE
);

END MARK_PACKAGE;
/

create PACKAGE BODY MARK_PACKAGE IS

    PROCEDURE ADD_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE, 
    MRK IN MARK.MARK%TYPE
    )
    IS
    BEGIN
    INSERT INTO MARK (CARD_ID, DISCIPLINE_NAME, ST_YEAR, MARK)
    VALUES (STDNT_ID, DSCPLN_NAME, STUDY_YEAR, MRK);
    COMMIT;
    END ADD_MARK;

    PROCEDURE DELETE_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE
    )
    IS
    BEGIN
    DELETE FROM DELETED_MARK
    WHERE DELETED_MARK.CARD_ID = STDNT_ID
    AND DELETED_MARK.DISCIPLINE_NAME = DSCPLN_NAME
    AND DELETED_MARK.ST_YEAR = STUDY_YEAR;
    COMMIT;
    END DELETE_MARK;

    PROCEDURE UPDATE_MARK(
    STDNT_ID IN STUDENT.CARD_ID%TYPE,
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE,
    MRK IN MARK.MARK%TYPE
    )
    IS
    BEGIN
    UPDATE MARK
    SET MARK.MARK = MRK
    WHERE MARK.CARD_ID = STDNT_ID
    AND MARK.DISCIPLINE_NAME = DSCPLN_NAME
    AND MARK.ST_YEAR = STUDY_YEAR;
    COMMIT;
    END UPDATE_MARK;

END MARK_PACKAGE;
/

