CREATE TABLE DISCIPLINE (
  DISCIPLINE_NAME VARCHAR2(30),
  CONSTRAINT PK_DISCIPLINE PRIMARY KEY (DISCIPLINE_NAME)
);

CREATE TABLE UNI_ROLE (
  ROLE_NAME VARCHAR2(30),
  CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_NAME)
);

CREATE TABLE HOMEWORK (
  DISCIPLINE_NAME VARCHAR2(30) NOT NULL,
  CONTRACT_ID VARCHAR2(30) NOT NULL,
  HW_DATE DATE NOT NULL,
  HW_DESCRIPTION VARCHAR2(300),
  CONSTRAINT PK_HW PRIMARY KEY (DISCIPLINE_NAME, CONTRACT_ID, HW_DATE)
);

ALTER TABLE HOMEWORK ADD CONSTRAINT FK_HW_DISCIPLINE
FOREIGN KEY (DISCIPLINE_NAME) REFERENCES DISCIPLINE (DISCIPLINE_NAME);

CREATE TABLE UNI_USER (
  USER_LOGIN VARCHAR2(8),
  USER_PASSWORD VARCHAR2(30) NOT NULL,
  ROLE_NAME VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_LOGIN)
);

CREATE TABLE STUDENT (
  USER_LOGIN VARCHAR2(8),
  CARD_ID VARCHAR2(30) NOT NULL,
  STUDENT_NAME VARCHAR2(30) NOT NULL,
  ST_SEMESTER NUMBER NOT NULL,
  CONSTRAINT PK_STUDENT PRIMARY KEY (USER_LOGIN),
  CONSTRAINT UNIQUE_STUDENT UNIQUE (CARD_ID)
);

CREATE TABLE TEACHER (
  USER_LOGIN VARCHAR2(8),
  CONTRACT_ID VARCHAR2(30) NOT NULL,
  TEACHER_NAME VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_TEACHER PRIMARY KEY (USER_LOGIN),
  CONSTRAINT UNIQUE_TEACHER UNIQUE (CONTRACT_ID)
);

ALTER TABLE UNI_USER ADD CONSTRAINT FK_ROLE_USER
FOREIGN KEY (ROLE_NAME) REFERENCES UNI_ROLE (ROLE_NAME);

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_USER
FOREIGN KEY (USER_LOGIN) REFERENCES UNI_USER (USER_LOGIN);

ALTER TABLE TEACHER ADD CONSTRAINT FK_TEACHER_USER
FOREIGN KEY (USER_LOGIN) REFERENCES UNI_USER (USER_LOGIN);

CREATE TABLE MARK (
  CARD_ID VARCHAR2(30) NOT NULL,
  DISCIPLINE_NAME VARCHAR2(30) NOT NULL,
  ST_YEAR DATE NOT NULL,
  MARK NUMBER,
  CONSTRAINT PK_MARK PRIMARY KEY (DISCIPLINE_NAME, CARD_ID, ST_YEAR)
);

ALTER TABLE MARK ADD CONSTRAINT FK_MARK_DISCIPLINE 
FOREIGN KEY (DISCIPLINE_NAME) REFERENCES DISCIPLINE (DISCIPLINE_NAME);

ALTER TABLE HOMEWORK ADD CONSTRAINT FK_HW_TEACHER
FOREIGN KEY (CONTRACT_ID) REFERENCES TEACHER (CONTRACT_ID);

ALTER TABLE MARK ADD CONSTRAINT FK_MARK_STUDENT
FOREIGN KEY (CARD_ID) REFERENCES STUDENT (CARD_ID);

ALTER TABLE MARK
ADD CONSTRAINT MARK_CHECK CHECK (MARK BETWEEN 0 AND 100);
