INSERT INTO DISCIPLINE (DISCIPLINE_NAME)
VALUES('DATA BASES');
INSERT INTO DISCIPLINE (DISCIPLINE_NAME)
VALUES ('OPERATING SYSTEMS');
INSERT INTO DISCIPLINE (DISCIPLINE_NAME)
VALUES ('ENGLISH');
INSERT INTO DISCIPLINE (DISCIPLINE_NAME)
VALUES ('ECONOMICS');

INSERT INTO HOMEWORK (DISCIPLINE, HOMEWORK_DATE, DESCRIPTION)
VALUES('DATA BASES', TO_DATE('2018/10/22', 'yyyy/mm/dd'),'CREATE USE CASE DIAGRAM');
INSERT INTO HOMEWORK (DISCIPLINE, HOMEWORK_DATE, DESCRIPTION)
VALUES ('OPERATING SYSTEMS', TO_DATE('2018/09/14', 'yyyy/mm/dd'),'PREPARE FOR A TEST');
INSERT INTO HOMEWORK (DISCIPLINE, HOMEWORK_DATE, DESCRIPTION)
VALUES ('ENGLISH', TO_DATE('2018/11/03', 'yyyy/mm/dd'),'WRITE MOTIVATION LETTER');
INSERT INTO HOMEWORK (DISCIPLINE, HOMEWORK_DATE, DESCRIPTION)
VALUES ('ECONOMICS', TO_DATE('2018/11/03', 'yyyy/mm/dd'),'READ AN ARTICLE ABOUT GDP IN EUROPE COUNTRIES');

INSERT INTO USERS (PASS_ID, USER_NAME, UNI_ROLE)
VALUES('TT509867', 'STUDENT1','STUDENT');
INSERT INTO USERS (PASS_ID, USER_NAME, UNI_ROLE)
VALUES ('EH890732', 'STUDENT2','STUDENT');
INSERT INTO USERS (PASS_ID, USER_NAME, UNI_ROLE)
VALUES ('OB254944', 'STUDENT3','STUDENT');
INSERT INTO USERS (PASS_ID, USER_NAME, UNI_ROLE)
VALUES ('PA330871', 'TEACHER1','TEACHER');

INSERT INTO MARK (USER_NAME, DISCIPLINE, MARK)
VALUES('STUDENT1','ENGLISH', 94);
INSERT INTO MARK (USER_NAME, DISCIPLINE, MARK)
VALUES ('STUDENT2','DATA BASES', 61);
INSERT INTO MARK (USER_NAME, DISCIPLINE, MARK)
VALUES ('STUDENT3','ECONOMICS', 73);
INSERT INTO MARK (USER_NAME, DISCIPLINE, MARK)
VALUES ('STUDENT3','ENGLISH', 60);
