CREATE OR REPLACE PACKAGE DISCIPLINE_PACKAGE AS

TYPE HW_DISCIPLINE_RECORD IS RECORD (
    TEACHER_NAME TEACHER.TEACHER_NAME%TYPE,
    HW_DATE HOMEWORK.HW_DATE%TYPE,
    HW_DESCRIPTION HOMEWORK.HW_DESCRIPTION%TYPE
);
TYPE HW_DISCIPLINE_TABLE IS 
    TABLE OF HW_DISCIPLINE_RECORD;
TYPE MARKS_DISCIPLINE_RECORD IS RECORD (
    STUDENT_NAME STUDENT.STUDENT_NAME%TYPE,
    MRK MARK.MARK%TYPE
);
TYPE MARKS_DISCIPLINE_TABLE IS 
    TABLE OF MARKS_DISCIPLINE_RECORD;

FUNCTION GET_DISCIPLINE_HW(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
)RETURN HW_DISCIPLINE_TABLE PIPELINED;

FUNCTION GET_DISCIPLINE_MARKS(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE
)RETURN MARKS_DISCIPLINE_TABLE PIPELINED;

PROCEDURE ADD_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
);

PROCEDURE DELETE_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
);

PROCEDURE UPDATE_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    NEW_DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
);

END DISCIPLINE_PACKAGE;

CREATE OR REPLACE PACKAGE BODY DISCIPLINE_PACKAGE IS
    
    FUNCTION GET_DISCIPLINE_HW(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
    )RETURN HW_DISCIPLINE_TABLE 
        PIPELINED
    IS
    BEGIN
    FOR PIECE IN (
        SELECT DISTINCT CONTRACT_ID, HW_DATE, HW_DESCRIPTION
        FROM HOMEWORK 
        WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    ) LOOP
        PIPE ROW (PIECE);
    END LOOP;
    END GET_DISCIPLINE_HW;

    FUNCTION GET_DISCIPLINE_MARKS(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    STUDY_YEAR IN MARK.ST_YEAR%TYPE
    )RETURN MARKS_DISCIPLINE_TABLE 
        PIPELINED
    IS
    BEGIN
    FOR PIECE IN (
        SELECT DISTINCT STUDENT.STUDENT_NAME, MARK.MARK
        FROM MARK JOIN STUDENT ON
        MARK.CARD_ID = STUDENT.CARD_ID
        WHERE MARK.DISCIPLINE_NAME = DSCPLN_NAME
        AND MARK.ST_YEAR = STUDY_YEAR
    ) LOOP
        PIPE ROW (PIECE);
    END LOOP;
    END GET_DISCIPLINE_MARKS;

    PROCEDURE ADD_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
    )
    IS
    BEGIN
    INSERT INTO DISCIPLINE (DISCIPLINE_NAME)
    VALUES (DSCPLN_NAME);
    COMMIT;
    END ADD_DISCIPLINE;

    PROCEDURE DELETE_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
    )
    IS
    BEGIN
    DELETE FROM DISCIPLINE
    WHERE DISCIPLINE.DISCIPLINE_NAME  = DSCPLN_NAME;
    COMMIT;
    END DELETE_DISCIPLINE;

    PROCEDURE UPDATE_DISCIPLINE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    NEW_DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE
    )
    IS
    BEGIN
    UPDATE DISCIPLINE 
    SET DISCIPLINE.DISCIPLINE_NAME = NEW_DSCPLN_NAME
    WHERE DISCIPLINE.DISCIPLINE_NAME = DSCPLN_NAME;
    COMMIT;
    END UPDATE_DISCIPLINE;

END DISCIPLINE_PACKAGE;