CREATE OR REPLACE PACKAGE HOMEWORK_PACKAGE AS

PROCEDURE ADD_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
);

PROCEDURE DELETE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
);

PROCEDURE UPDATE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
);

END HOMEWORK_PACKAGE;

CREATE OR REPLACE PACKAGE BODY HOMEWORK_PACKAGE IS

    PROCEDURE ADD_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
    )
    IS
    BEGIN
    INSERT INTO HOMEWORK (DISCIPLINE_NAME, CONTRACT_ID, HW_DATE, HW_DESCRIPTION)
    VALUES (DSCPLN_NAME, TCHR_ID, HMWRK_DATE, HMWRK_DESCRIPTION);
    COMMIT;
    END ADD_HOMEWORK;

    PROCEDURE DELETE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
    )
    IS
    BEGIN
    DELETE FROM HOMEWORK
    WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    AND HOMEWORK.CONTRACT_ID = TCHR_ID
    AND HOMEWORK.HW_DATE = HMWRK_DATE ;
    COMMIT;
    END DELETE_HOMEWORK;

    PROCEDURE UPDATE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
    )
    IS
    BEGIN
    UPDATE HOMEWORK
    SET HOMEWORK.HW_DESCRIPTION = HMWRK_DESCRIPTION
    WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    AND HOMEWORK.CONTRACT_ID = TCHR_ID
    AND HOMEWORK.HW_DATE = HMWRK_DATE ;
    COMMIT;
    END UPDATE_HOMEWORK;

END HOMEWORK_PACKAGE;