create PACKAGE HOMEWORK_PACKAGE AS

FUNCTION TNAME_TO_ID(
    T_NAME  TEACHER.TEACHER_NAME%TYPE
    )RETURN VARCHAR2;

PROCEDURE ADD_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
);

PROCEDURE DELETE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
);

PROCEDURE UPDATE_HOMEWORK_DESCRIPTION(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
);

PROCEDURE UPDATE_HOMEWORK_DATE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    NEW_HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
);

FUNCTION FIND_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
) RETURN NUMBER;

END HOMEWORK_PACKAGE;
/

create PACKAGE BODY HOMEWORK_PACKAGE IS

  FUNCTION TNAME_TO_ID(
    T_NAME  TEACHER.TEACHER_NAME%TYPE
    )RETURN VARCHAR2 IS
    tid VARCHAR2(30);
    BEGIN
    SELECT
    CONTRACT_ID
    INTO tid
    FROM TEACHER
        WHERE TEACHER_NAME = T_NAME;
    return(tid);
    END TNAME_TO_ID;

   PROCEDURE ADD_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
    )
    IS
    BEGIN
    INSERT INTO HOMEWORK (DISCIPLINE_NAME, CONTRACT_ID, HW_DATE, HW_DESCRIPTION)
    VALUES (DSCPLN_NAME, TCHR_ID, HMWRK_DATE, HMWRK_DESCRIPTION);
    COMMIT;
    END ADD_HOMEWORK;

    PROCEDURE DELETE_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
    )
    IS
    BEGIN
    DELETE FROM HOMEWORK
    WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    AND HOMEWORK.CONTRACT_ID = TCHR_ID
    AND HOMEWORK.HW_DATE = HMWRK_DATE ;
    COMMIT;
    END DELETE_HOMEWORK;

    PROCEDURE UPDATE_HOMEWORK_DESCRIPTION(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    HMWRK_DESCRIPTION IN HOMEWORK.HW_DESCRIPTION%TYPE
    )
    IS
    BEGIN
    UPDATE HOMEWORK
    SET HOMEWORK.HW_DESCRIPTION = HMWRK_DESCRIPTION
    WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    AND HOMEWORK.CONTRACT_ID = TCHR_ID
    AND HOMEWORK.HW_DATE = HMWRK_DATE ;
    COMMIT;
    END UPDATE_HOMEWORK_DESCRIPTION;

    PROCEDURE UPDATE_HOMEWORK_DATE(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE,
    NEW_HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
    )
    IS
    BEGIN
    UPDATE HOMEWORK
    SET HOMEWORK.HW_DATE = NEW_HMWRK_DATE
    WHERE HOMEWORK.DISCIPLINE_NAME = DSCPLN_NAME
    AND HOMEWORK.CONTRACT_ID = TCHR_ID
    AND HOMEWORK.HW_DATE = HMWRK_DATE ;
    COMMIT;
    END UPDATE_HOMEWORK_DATE;

   FUNCTION FIND_HOMEWORK(
    DSCPLN_NAME IN DISCIPLINE.DISCIPLINE_NAME%TYPE,
    TCHR_ID IN TEACHER.CONTRACT_ID%TYPE,
    HMWRK_DATE IN HOMEWORK.HW_DATE%TYPE
    ) RETURN NUMBER
    IS RES NUMBER(1);
    BEGIN
    SELECT COUNT(*)
    INTO RES
    FROM HOMEWORK
    WHERE (DISCIPLINE_NAME = DSCPLN_NAME)
      AND (CONTRACT_ID = TCHR_ID)
      AND (HW_DATE = HMWRK_DATE);
    RETURN RES;
    END FIND_HOMEWORK;

END HOMEWORK_PACKAGE;
/

